/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

/* Header for class com_annotion_ruiyi_testsolog_JniHelper */

#ifndef _Included_com_annotion_ruiyi_testsolog_JniHelper
#define _Included_com_annotion_ruiyi_testsolog_JniHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_annotion_ruiyi_testsolog_JniHelper
 * Method:    showLog
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_annotion_ruiyi_testsolog_JniHelper_showLog
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
